### ISSUE TITLE
On-demand downloading or incremental installation?

### ISSUE THREAD

**Issue by ice1000** [cargo-bins/cargo-quickinstall#115]
Can we have a feature that only installs the software when the downloadable version is newer?

**Comment by NobodyXu** [comment]
This is related to #71, it basically requires `cargo-quickinstall` to update the manifest in `$CARGO_HOME/.crates.toml` or use `cargo-binstall` for installation.

**Comment by ice1000** [comment]
Thanks for the quick answer!
