### ISSUE TITLE
Filter out crates with no binary

### ISSUE THREAD

**Issue by NobodyXu** [cargo-bins/cargo-quickinstall#167]
When running weekly check on #163, I noticed that it tries to build [ build watchexec 2.1.1 on x86_64-unknown-linux-gnu](https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4336384815/jobs/7571629066) but failed because watchexec does not provide any binary.

**Comment by NobodyXu** [comment]
Turns out that this is impossible unless we download the crate tarball, extract `Cargo.toml`, `src/main.rs` and everything under `src/bin` for inferring the bins.

**Comment by NobodyXu** [comment]
Thanks you!

We were actually looking for something that doesn't depend on crates.io API (it's has rate limit) as an optimization to avoid triggering build for library, but since it's just an optimization we don't have much motivation to add it now

**Comment by Azathothas** [comment]
I parsed over a 100,000 crates, these were the results:
```bash
[+] Total Packages: 111708
[+] Binary Packages: 24650
```

Data: https://github.com/pkgforge-cargo/builder/raw/refs/heads/main/data/CRATES_DUMP.json
Each crate has a `has_bins` section, which denotes true or false
