### ISSUE TITLE
Different releases of same crate has different set artifacts each release.

### ISSUE THREAD

**Issue by mstyura** [cargo-bins/cargo-quickinstall#227]
I've not yet figured out how, but it seems like there is a problem(?) with pre-built artifacts publishing. It seems like it's very often different releases of same crate has different set of target platforms built. Here is some examples of the crates I'm interested in:
1. [cargo-nextest-0.9.57](https://github.com/cargo-bins/cargo-quickinstall/tree/cargo-nextest-0.9.57):
    - cargo-nextest-0.9.57-aarch64-apple-darwin.tar.gz
    - cargo-nextest-0.9.57-x86_64-apple-darwin.tar.gz
    - cargo-nextest-0.9.57-x86_64-pc-windows-msvc.tar.gz
    - cargo-nextest-0.9.57-x86_64-unknown-linux-gnu.tar.gz
    - cargo-nextest-0.9.57-x86_64-unknown-linux-musl.tar.gz 
1. [cargo-nextest-0.9.55](https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-nextest-0.9.55)
    - cargo-nextest-0.9.55-aarch64-apple-darwin.tar.gz
    - cargo-nextest-0.9.55-aarch64-unknown-linux-musl.tar.gz
    - cargo-nextest-0.9.55-x86_64-apple-darwin.tar.gz
    - cargo-nextest-0.9.55-x86_64-pc-windows-msvc.tar.gz
    - cargo-nextest-0.9.55-x86_64-unknown-linux-gnu.tar.gz
    - cargo-nextest-0.9.55-x86_64-unknown-linux-musl.tar.gz 
1. [cargo-nextest-0.9.54](https://github.com/cargo-bins/cargo-quickinstall/tree/cargo-nextest-0.9.54)
    - cargo-nextest-0.9.54-aarch64-apple-darwin.tar.gz
    - cargo-nextest-0.9.54-aarch64-unknown-linux-gnu.tar.gz
    - cargo-nextest-0.9.54-aarch64-unknown-linux-musl.tar.gz
    - cargo-nextest-0.9.54-x86_64-apple-darwin.tar.gz
    - cargo-nextest-0.9.54-x86_64-pc-windows-msvc.tar.gz
    - cargo-nextest-0.9.54-x86_64-unknown-linux-gnu.tar.gz
    - cargo-nextest-0.9.54-x86_64-unknown-linux-musl.tar.gz 
1. [cargo-llvm-cov-0.5.31](https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-llvm-cov-0.5.31)
    - cargo-llvm-cov-0.5.31-aarch64-apple-darwin.tar.gz
    - cargo-llvm-cov-0.5.31-aarch64-pc-windows-msvc.tar.gz
    - cargo-llvm-cov-0.5.31-x86_64-apple-darwin.tar.gz
    - cargo-llvm-cov-0.5.31-x86_64-pc-windows-msvc.tar.gz
    - cargo-llvm-cov-0.5.31-x86_64-unknown-linux-gnu.tar.gz 
1. [cargo-llvm-cov-0.5.30](https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-llvm-cov-0.5.30)
    - cargo-llvm-cov-0.5.30-aarch64-apple-darwin.tar.gz
    - cargo-llvm-cov-0.5.30-x86_64-apple-darwin.tar.gz
    - cargo-llvm-cov-0.5.30-x86_64-unknown-linux-gnu.tar.gz 
1. [cargo-llvm-cov-0.5.29](https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-llvm-cov-0.5.29)
    -  cargo-llvm-cov-0.5.29-x86_64-unknown-linux-gnu.tar.gz 

Is this something known and inevitable, or could be potentially fixed?

**Comment by NobodyXu** [comment]
It's built when requested (i.e. hitting the API), we can fix this by adding to the popular-list that is always built.

#226 should fix this.

**Comment by NobodyXu** [comment]
There's some problems with cross compiling due to latest zig reject unknown link flag.

I will submit a PR later to downgrade it.

**Comment by NobodyXu** [comment]
@mstyura cargo-nextest v0.9.57 now has artifacts uploaded for all targets except for aarch64 windows https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-nextest-0.9.57

cargo-llvm-cov v0.5.31 now has artifacts uploaded for all targets https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-llvm-cov-0.5.31
