### ISSUE TITLE
Failed to HEAD warehouse-clerk-tmp.vercel.app

### ISSUE THREAD

**Issue by NobodyXu** [cargo-bins/cargo-quickinstall#246]
```
 WARN Failed to send quickinstall report for package kani-verifier-0.47.0-aarch64-apple-darwin: Failed to download from remote: could not HEAD https://warehouse-clerk-tmp.vercel.app/api/crate/kani-verifier-0.47.0-aarch64-apple-darwin.tar.gz: HTTP status server error (500 Internal Server Error) for url (https://warehouse-clerk-tmp.vercel.app/api/crate/kani-verifier-0.47.0-aarch64-apple-darwin.tar.gz)
```

cc @alsuren seems like warehouse is down or something?

Has been seeing this for a while on my computer.

**Comment by alsuren** [comment]
Hi. Sorry for the delay. This showed up in the talk from the release-plz maintainer. As a work-around, I added a try/catch around my calls to redis so you shouldn't see this anymore.

We still report to both redis and influxdb (via fly.io). I should really finish the transition to influxdb at some point.
