### ISSUE TITLE
Broken build for jj-cli

### ISSUE THREAD

**Issue by senekor** [cargo-bins/cargo-quickinstall#250]
[related issue in the jj repo](https://github.com/martinvonz/jj/issues/3844)

jj provides [prebuilt binaries itself](https://github.com/martinvonz/jj/releases/tag/v0.18.0), but only statically linked against musl on linux. Which is fine, because that works on any linux system, whatever the system libc is. However, `cargo binstall jj-cli` fell back to the (borked) binary provided by quickinstall. I did not notice this at first, even though it does say so in the output of `cargo-binstall`.

I'm not sure what the right thing to do here is, but having `cargo-binstall` install from a different source than the official one, even though the official one does in fact provide binaries, is incredibly confusing.

**Comment by senekor** [comment]
for reference, this seems to be [the CI job that built jj](https://github.com/cargo-bins/cargo-quickinstall/actions/runs/9410274128)

**Comment by NobodyXu** [comment]
We use glibc 2.17, probably that's the reason of the failure?

**Comment by polarathene** [comment]
> We use glibc 2.17, probably that's the reason of the failure?

As per linked discussion comment, yes glibc 2.33 would avoid the issue, **or** updating CI from Zig 0.10.0 to a version from Zig 0.12.0 (_you have many CI runs apparently failing when I was looking over workflow history, not sure if this subtle bug affects other bins you distribute_).

**Comment by NobodyXu** [comment]
Previously we have some build failure with newer zig-cc (I think it might be related to cargo-auditable)

**Comment by polarathene** [comment]
If you have more context on that failure it would be good to know. Perhaps it was also fixed from Zig 0.12.0? I like to use zig for builds but I am a little wary at times due to these non-obvious caveats/surprises occurring 😓

**Comment by NobodyXu** [comment]
> If you have more context on that failure it would be good to know.

rust-cross/cargo-zigbuild#162

IIRC the upstream issue in zig-cc is still open 

Anyway we don't use cargo-audiable anymore (because it can be overwritten by the crate), I have bumped zig-cc to latest version
