### ISSUE TITLE
Install failures with last update

### ISSUE THREAD

**Issue by larseggert** [cargo-bins/cargo-quickinstall#267]
https://github.com/mozilla/neqo/actions/runs/10318035494/job/28563547145?pr=2047#step:3:338
```
Run cargo +1.76.0 quickinstall --no-binstall $(echo cargo-llvm-cov, cargo-nextest, cargo-hack, cargo-fuzz, cargo-machete | tr -d ",")
Installed cargo-llvm-cov@0.6.11 to /Users/runner/.cargo/bin:
x -rwxr-xr-x  0 501    20    3456240 Jul 18 17:24 cargo-llvm-cov
Installed cargo-nextest@0.9.72 to /Users/runner/.cargo/bin:
x -rwxr-xr-x  0 501    20   11412240 May 23 21:25 cargo-nextest
Error: Command failed:
    curl --user-agent "cargo-quickinstall/0.2.11 client (alsuren@gmail.com)" --location --silent --show-error --fail "https://github.com/cargo-bins/cargo-quickinstall/releases/download/cargo-hack-0.6.31/cargo-hack-0.6.31-aarch64-apple-darwin.tar.gz"
Stderr:
curl: (56) The requested URL returned error: 404

Error: Process completed with exit code 1.
```

**Comment by NobodyXu** [comment]
I don't think it's a probl with cargo-quickinstall

https://github.com/cargo-bins/cargo-quickinstall/releases/tag/cargo-hack-0.6.31

Rather it's that this target of cargo-hack isn't build on quickinstall.

I recommend removing `--no-binstall` since it could try installing cargo-hack from its official repositories.

**Comment by larseggert** [comment]
Thanks! I guess both packages had releases yesterday.

**Comment by larseggert** [comment]
`binstall` seems to have issues, too: https://github.com/mozilla/neqo/actions/runs/10318742667/job/28565725822?pr=2046#step:3:367

**Comment by NobodyXu** [comment]
Aha it's rate limited, I recommend to pass a `GITHUB_TOKEN` to it via environment variable.

**Comment by larseggert** [comment]
I'm sorry, but *what* should I pass `GITHUB_TOKEN` to?

**Comment by NobodyXu** [comment]
> I'm sorry, but *what* should I pass `GITHUB_TOKEN` to?

I'd recommend you to pass it to `cargo-binstall`, or the `cargo-quickinstall` which invokes `cargo-binatall.`

Usually I do `secrets.GITHUB_TOKEN`, you could create a specialised token for it if you used it very frequently (repo-wide token is limited to 1k per hour, user created token is 5k per hour) or you have security concerns you can create one yourself and limit its permissions.

You could also limit `secrets.GITHUB_TOKEN`via `permissions` setting in GHA.

The reason it's necessary, is that many crates do not provide configuration for this on github, so we have to discover them ourselves, which often gets rate limited.
