### ISSUE TITLE
get `cargo-quickinstall` included in https://github.com/actions-rs/cargo or something?

### ISSUE THREAD

**Issue by alsuren** [cargo-bins/cargo-quickinstall#42]
https://github.com/marketplace/actions/rust-cargo-install feels like it does what we want, but feels deprecated. Maybe dig into why that is?

It may be that we can write a patch to cargo-bincode to install binaries from our github-releases?

**Comment by NobodyXu** [comment]
I have added cargo-binstall to https://github.com/taiki-e/install-action , which installs popular crates for rust CI from binary (including non-rust one).

Though it is not the official one, there are people using it.

**Comment by alsuren** [comment]
> I have added cargo-binstall to https://github.com/taiki-e/install-action , which installs popular crates for rust CI from binary (including non-rust one).
> 
> Though it is not the official one, there are people using it.

As long as it's an action that can install from the quickinstall repo, that's good enough for me. Just need to mention it in the readme and then we can close this issue.
