### ISSUE TITLE
Always says it's installing to `~/.cargo/bin` even when it's not

### ISSUE THREAD

**Issue by kkysen** [cargo-bins/cargo-quickinstall#79]
If `$CARGO_HOME` is not `~/.cargo`, `cargo quickinstall` still says it's installing to `~/.cargo/bin`, which is quite confusing.  If it could be updated to correctly show where it was installed, that would be great.

For example, 
```shell
> mkdir bin
> CARGO_HOME=. cargo quickinstall ripgrep
Installed ripgrep 13.0.0 to ~/.cargo/bin:
-rwxr-xr-x runner/docker 28338504 2021-06-12 09:38 rg
> ll bin
.rwxr-xr-x  28M kkysen 12 Jun  2021 rg*
```

**Comment by alsuren** [comment]
Week spotted. Thanks for the bug report.

I'm at festival until Monday, so I might not get around to fixing this until next weekend. If you can see an easy way to fix it, I'm happy to merge PRs from my phone.
